#!/usr/bin/env Rscript
# Markdown tables from the MICS inventory: all 93 surveys by round and file, and the
# birth-history surveys with their sizes and covariate sources. Aggregate only.
suppressPackageStartupMessages(library(data.table))
out <- "results/mics_inventory"
inv <- fread(file.path(out, "survey_inventory.csv"))
fmt <- function(x) ifelse(is.na(x), "--", format(x, big.mark = ",", trim = TRUE))
yn <- function(x) ifelse(is.na(x) | x %in% c("", "NA", FALSE), "no", "yes")
lab <- function(s) sub("_v01_M$", "", s)

by_round <- inv[, .(surveys = .N, with_birth_history = sum(has_bh)), by = .(round = paste0("MICS", round))][order(round)]
md <- c("# MICS microdata inventory", "",
  "Generated by `R_mics/01_inventory.R` and `R_mics/02_inventory_tables.R` from the SPSS files in `data/MICS_extracted/` (git-ignored). Only aggregate counts and variable names are reported here.", "",
  "## Surveys by round", "", "| Round | Surveys | With a complete birth history |", "|---|---:|---:|",
  sprintf("| %s | %d | %d |", by_round$round, by_round$surveys, by_round$with_birth_history),
  sprintf("| **All** | **%d** | **%d** |", nrow(inv), sum(inv$has_bh)), "",
  "MICS2 (2000) collected no birth history. MICS3 and MICS4 carried the full birth-history module in only some countries; the others asked summary questions (children ever born, children dead, date of last birth), which cannot support the child age-band design. Every MICS5 and MICS6 survey here has a full birth history.", "",
  "## Surveys with a complete birth history", "",
  "Births and deaths are counted from the birth-history file. \"Last 5 years\" counts births in the 60 months before the woman's interview and, among them, deaths before age five; this approximates, but is not identical to, the band-entry eligibility used in the primary analysis.", "",
  "| Survey | Interview year | Regions | Births | Births, last 5 y | Under-5 deaths, last 5 y | Anthropometry | Facility delivery |",
  "|---|---:|---:|---:|---:|---:|---|---|")
b <- inv[has_bh == TRUE][order(iso3, year)]
md <- c(md, sprintf("| %s | %s | %s | %s | %s | %s | %s | %s |", lab(b$survey), fmt(b$interview_year),
  fmt(b$n_regions), fmt(b$births), fmt(b$births_last5y), fmt(b$deaths_last5y_under5),
  yn(b$whz_var), yn(b$delivery_var)))
md <- c(md, sprintf("| **Total, %d surveys** | | | **%s** | **%s** | **%s** | | |", nrow(b),
  fmt(sum(b$births)), fmt(sum(b$births_last5y)), fmt(sum(b$deaths_last5y_under5))), "",
  "## Surveys without a complete birth history", "",
  paste(sprintf("%s", lab(inv[has_bh == FALSE][order(round, iso3)]$survey)), collapse = ", "), "")
writeLines(md, file.path(out, "INVENTORY.md"))
cat("Inventory tables written:", file.path(out, "INVENTORY.md"), "\n")
